name: PR to main Opened
on: 
  pull_request:
    types: 
      - opened
    branches:
      - main

jobs: 
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t eddy4r.york .

      - name: Check
        run: docker run --rm eddy4r.york Rscript /home/york/runtests.r

